# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, verbose_name='url路径')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='错误的首次生成时间')),
                ('count', models.IntegerField(default=1, verbose_name='错误记录数')),
                ('last_send_time', models.DateTimeField(verbose_name='最后一次向邮箱发送警报的时间')),
                ('state', models.CharField(choices=[('1', '未处理'), ('2', '已处理')], default='1', max_length=2, verbose_name='')),
                ('solve_time', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '程序错误信息',
                'verbose_name_plural': '程序错误信息',
                'db_table': 'alipay_log',
            },
        ),
    ]
