# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, verbose_name='url路径')),
                ('break_time', models.DateTimeField(blank=True, null=True, verbose_name='url瘫痪时间')),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '瘫痪中')], default='1', max_length=2,
                                           verbose_name='url状态')),
                ('msg',
                 models.CharField(default='该服务正在维护，暂停使用。请各位用户谅解，对您造成的不便，我们深表歉意。', max_length=60, verbose_name='url状态')),
            ],
            options={
                'verbose_name': '程序url状态',
                'verbose_name_plural': '程序url状态',
            },
        ),
        migrations.AlterField(
            model_name='error_msg',
            name='state',
            field=models.CharField(choices=[('1', '未处理'), ('2', '已处理')], default='1', max_length=2,
                                   verbose_name='错误处理进度'),
        ),
    ]
