# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180629_0936'),
        ('Log', '0002_auto_20180108_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombboxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('content', models.CharField(default='', max_length=150, verbose_name='内容')),
                ('state', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '弹框信息',
                'verbose_name_plural': '弹框信息',
                'db_table': 'alipay_bombboxinfo',
            },
        ),
        migrations.CreateModel(
            name='CancelBombboxInfoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bombbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Log.BombboxInfo', verbose_name='弹框信息')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OpenUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '取消弹框记录',
                'verbose_name_plural': '取消弹框记录',
            },
        ),
        migrations.CreateModel(
            name='UserOperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50, verbose_name='url路径')),
                ('incident', models.CharField(max_length=50, verbose_name='事件（自定义）')),
                ('count', models.IntegerField(default=1, verbose_name='记录数')),
                ('creat_time_by_minutes', models.DateTimeField(auto_now_add=True, verbose_name='产生时间(精确到分钟)')),
                ('creat_time_by_day', models.DateField(auto_now_add=True, verbose_name='产生时间(精确到天)')),
                ('request_data', models.TextField(verbose_name='请求数据')),
                ('response_data', models.TextField(verbose_name='返回数据')),
                ('run_time', models.TextField(verbose_name='运行时间（秒）')),
                ('Field1', models.CharField(max_length=50, verbose_name='保留字段1')),
                ('Field2', models.CharField(max_length=50, verbose_name='保留字段2')),
                ('Field3', models.CharField(max_length=50, verbose_name='保留字段3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OpenUser', verbose_name='支付宝用户')),
            ],
            options={
                'verbose_name': '用户行为记录',
                'verbose_name_plural': '用户行为记录',
            },
        ),
    ]
